name: Readme Workflow
on:
  push:
    branches:
      - master
    paths-ignore:
      - 'README.md'
      - 'docs/**'
  workflow_dispatch:
jobs:
  README:
    uses: clouddrove/github-shared-workflows/.github/workflows/readme.yml@1.3.6
    secrets:
      TOKEN : ${{ secrets.CD_GITHUB }}
      SLACK_WEBHOOK_TERRAFORM: ${{ secrets.SLACK_WEBHOOK_TERRAFORM }}